// bundle beer action types into single object
export const beerActionTypes = {
  FETCH_PLATFORMAPPS: "FETCH_PLATFORMAPPS",
  FETCHING_PLATFORMAPPS: "FETCHING_PLATFORMAPPS",
  FETCH_MORE_PLATFORMAPPS: "FETCH_MORE_PLATFORMAPPS",
  SEARCH_PLATFORMAPPS: "SEARCH_PLATFORMAPPS",
  HANDLE_FAVOURITE_PLATFORMAPP: "HANDLE_FAVOURITE_PLATFORMAPP",
  DISPLAY_PLATFORMAPP: "DISPLAY_PLATFORMAPP",
  FETCH_BEERS: "FETCH_BEERS",
  FETCHING_BEERS: "FETCHING_BEERS",
  FETCH_MORE_BEERS: "FETCH_MORE_BEERS",
  SEARCH_BEERS: "SEARCH_BEERS",
  HANDLE_FAVOURITE_BEER: "HANDLE_FAVOURITE_BEER",
  DISPLAY_BEER: "DISPLAY_BEER"
};
